# Generated by Django 4.2.23 on 2025-06-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('streak', models.IntegerField(default=0)),
                ('hobbies', models.JSONField(default=user.models.default_hobbies)),
            ],
        ),
    ]
