# Generated by Django 4.2.23 on 2025-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bed_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='day_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='morning_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
