# Generated by Django 4.2.23 on 2025-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_points_alter_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prev_scores',
            field=models.JSONField(default=dict),
        ),
    ]
