# Generated by Django 4.2.23 on 2025-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
