# Generated by Django 4.2.23 on 2025-08-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
