# Generated by Django 4.2.23 on 2025-07-02 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-10)'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('test', 'Text')], max_length=30)),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tracking.questionaire')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tracking.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('choices', models.ManyToManyField(blank=True, to='tracking.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
