# Generated by Django 4.2.23 on 2025-07-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_question_choice_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='affects_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='type',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Daytime'), ('bed', 'Bedtime')], default='e', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating (1-10)'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('text', 'Text')], max_length=30),
        ),
        migrations.CreateModel(
            name='QuestionaireScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.questionaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
