# Generated by Django 4.2.23 on 2025-07-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0003_rename_question_choice_question_answer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_score',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='depends_one_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionairescore',
            unique_together={('user', 'questionaire', 'date')},
        ),
    ]
