# Generated by Django 4.2.23 on 2025-07-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_choice_choice_score_question_depends_one_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='depends_one_question',
            new_name='depends_on_question',
        ),
    ]
