# Generated by Django 4.2.23 on 2025-07-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_rename_depends_one_question_question_depends_on_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_optional',
            field=models.BooleanField(default=True),
        ),
    ]
