# Generated by Django 4.2.23 on 2025-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_question_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
