# Generated by Django 4.2.23 on 2025-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Elite', 'Elite'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=20)),
                ('sprite', models.CharField(default='creatures/', max_length=200)),
                ('icon', models.CharField(default='creatures/', max_length=200)),
            ],
        ),
    ]
