# Generated by Django 4.2.23 on 2025-07-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Elite', 'Elite'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=20, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('hatch_requirement', models.PositiveBigIntegerField(default=3)),
                ('sprite', models.CharField(help_text='eggs/', max_length=200)),
                ('hatch_sprites', models.JSONField(default=list, help_text='list of hatching sprites')),
            ],
        ),
        migrations.CreateModel(
            name='UserEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatures.egg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveBigIntegerField(default=1)),
                ('last_fed_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatures.creature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'creature')},
            },
        ),
    ]
