# Generated by Django 4.2.23 on 2025-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_egg_useregg_usercreature'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreature',
            name='reached_max_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useregg',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
