# Generated by Django 4.2.23 on 2025-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0003_usercreature_reached_max_level_useregg_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreature',
            old_name='reached_max_level',
            new_name='is_hibernating',
        ),
        migrations.AddField(
            model_name='usercreature',
            name='hibernating_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreature',
            name='hunger_delay_hours',
            field=models.PositiveBigIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='usercreature',
            name='hungry_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreature',
            name='last_level_drop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
