# Generated by Django 4.2.23 on 2025-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0004_rename_reached_max_level_usercreature_is_hibernating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreature',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
